language: node_js
sudo: false

node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

after_success:
  - npm run coverage
  - npm i coveralls
  - cat ./coverage/lcov.info | coveralls

notifications:
  email: false

cache:
  directories:
  - node_modules
